ORDER_STATUS_PENDING_PAYMENT = "pending_payment"
ORDER_STATUS_PAID = "paid"
ORDER_STATUS_BAKING = "baking"
ORDER_STATUS_READY_PICKUP = "ready_pickup"
ORDER_STATUS_FINISHED = "finished"
ORDER_STATUS_CANCELLED = "cancelled"

ORDER_STATUS_TEXT_MAP = {
    ORDER_STATUS_PENDING_PAYMENT: "待支付",
    ORDER_STATUS_PAID: "已支付",
    ORDER_STATUS_BAKING: "制作中",
    ORDER_STATUS_READY_PICKUP: "待取货",
    ORDER_STATUS_FINISHED: "已完成",
    ORDER_STATUS_CANCELLED: "已取消",
}

ACTIVE_STATUS = "enabled"
DISABLED_STATUS = "disabled"
GOODS_STATUS_ON = "on"
GOODS_STATUS_OFF = "off"
TOKEN_TYPE_ADMIN = "admin"
TOKEN_TYPE_USER = "user"

POINTS_PRODUCT_STATUS_ENABLED = "enabled"
POINTS_PRODUCT_STATUS_DISABLED = "disabled"

POINTS_REDEMPTION_STATUS_PENDING = "pending"
POINTS_REDEMPTION_STATUS_FULFILLED = "fulfilled"
POINTS_REDEMPTION_STATUS_CANCELLED = "cancelled"

POINTS_TRANSACTION_TYPE_WELCOME_BONUS = "welcome_bonus"
POINTS_TRANSACTION_TYPE_ORDER_REWARD = "order_reward"
POINTS_TRANSACTION_TYPE_REDEEM_SPEND = "redeem_spend"
POINTS_TRANSACTION_TYPE_REDEEM_REFUND = "redeem_refund"
